/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,jsx}',
    './src/components/**/*.{js,jsx}',
    './src/app/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#dce9ff",
        "surface-container": "#e5eeff",
        "primary": "#091426",
        "secondary-fixed": "#e3dfff",
        "tertiary-container": "#00301f",
        "inverse-on-surface": "#eaf1ff",
        "secondary-container": "#6860ef",
        "on-tertiary-fixed": "#002114",
        "primary-container": "#1e293b",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#3c475a",
        "on-secondary-fixed-variant": "#372abf",
        "tertiary": "#00190e",
        "on-secondary-container": "#fffbff",
        "surface-variant": "#d3e4fe",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "tertiary-fixed-dim": "#68dba9",
        "surface-container-highest": "#d3e4fe",
        "on-primary-container": "#8590a6",
        "secondary-fixed-dim": "#c3c0ff",
        "surface": "#f8f9ff",
        "on-tertiary-fixed-variant": "#005137",
        "inverse-surface": "#213145",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#85f8c4",
        "outline": "#75777d",
        "on-tertiary-container": "#24a375",
        "secondary": "#4e45d5",
        "inverse-primary": "#bcc7de",
        "outline-variant": "#c5c6cd",
        "on-surface": "#0b1c30",
        "error-container": "#ffdad6",
        "surface-container-low": "#eff4ff",
        "on-background": "#0b1c30",
        "surface-tint": "#545f73",
        "background": "#f8f9ff",
        "on-error": "#ffffff",
        "primary-fixed": "#d8e3fb",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#45474c",
        "surface-dim": "#cbdbf5",
        "primary-fixed-dim": "#bcc7de",
        "on-primary-fixed": "#111c2d",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#100069",
        // Keep some old background gradient configurations if needed, but redefine them with the new colors
        'hero-gradient': 'linear-gradient(135deg, #091426 0%, #4e45d5 100%)',
        'card-gradient': 'linear-gradient(135deg, #4e45d5 0%, #6860ef 100%)',
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "xs": "4px",
        "unit": "4px",
        "md": "16px",
        "lg": "24px",
        "sm": "8px",
        "xl": "32px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "xxl": "48px"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        "display-md": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["10px", {"lineHeight": "1", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "1", "fontWeight": "500"}],
        "headline-sm": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "label-lg": ["14px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg": ["30px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}]
      },
    },
  },
  plugins: [],
};
